# Generated by Django 6.0.2 on 2026-04-06 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0002_comment_task_project_creator_project_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
